development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:94fe2bfd88879a9a682b3e349fbdffc5@spinyfin.redistogo.com:11357/
  # channel_prefix: bookclone_production
